GestionaleMunicipale/Models/Anagrafica.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Municipale.Models
{
    public class Anagrafica
    {
        public int IDAnagrafica { get; set; }

        [Required]
        [StringLength(20)]
        public string Cognome { get; set; }

        [Required]
        [StringLength(20)]
        public string Nome { get; set; }

        [Required]
        [StringLength(50)]
        public string Indirizzo { get; set; }

        [Required]
        [StringLength(20)]
        public string Citta { get; set; }

        [StringLength(5)]
        public string CAP { get; set; }

        [Required]
        [StringLength(16)]
        [Display(Name = "Codice Fiscale")]
        public string Cod_Fisc { get; set; }
       
        [Display(Name = "Verbali")]
        public int totVerbali {  get; set; }

        [Display(Name = "totale punti decurtati")]
        public int totPuntiDecurtati { get; set; }

        public Anagrafica() { }
        public Anagrafica(int id,string nome,string cognome, string indirizzo,string citta, string cap,string codFiscale) 
        { 
            IDAnagrafica = id;
            Nome = nome;
            Cognome = cognome;
            Indirizzo = indirizzo;
            Citta = citta;
            CAP = cap;
            Cod_Fisc= codFiscale;
        }


    }
}

GestionaleMunicipale/Models/TipoViolazione.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Municipale.Models
{
    public class TipoViolazione
    {
        public int IdViolazione { get; set; }

        [Required]
        public string Descrizione { get; set; }

        public TipoViolazione(int id, string descrizione) 
        { 
            IdViolazione = id;
            Descrizione = descrizione;
        }

        public TipoViolazione() { }
    }
}

GestionaleMunicipale/Models/Verbale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Municipale.Models
{
    public class Verbale
    {
        public int IDVerbali { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Data Violazione")]
        public DateTime DataViolazione { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Indirizzo Violazione")]
        public string IndirizzoViolazione { get; set; }

        [Required]
        [StringLength(30)]
        [Display(Name = "Agente")]
        public string Nominativo_Agente { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Data Verbale")]
        public DateTime DataTrascrizioneVerbale { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal Importo { get; set; }

        [Required]
        [Display(Name = "Punti decurtati")]
        public int DecrementoPunti { get; set; }

        [Required]
        public int IDAnagrafica { get; set; }

        [Required]
        public int IDViolazione { get; set; }

        [Display(Name="Nome")]
        public string NomeAnagrafica { get; set; }
        
        [Display(Name = "Cognome")]
        public string  CognomeAnagrafica { get; set; }
        
        
        [Display(Name = "Violazione")]
        public string TipoViolazione {get; set; }

        public Verbale() { }
        public Verbale(int idVerbali, DateTime dataViolazione, string indirizzoViolazione, string nominativoAgente, DateTime dataTrascrizioneVerbale, decimal importo, int decrementoPunti, int idAnagrafica, int idViolazione)
        {
            IDVerbali = idVerbali;
            DataViolazione = dataViolazione;
            IndirizzoViolazione = indirizzoViolazione;
            Nominativo_Agente = nominativoAgente;
            DataTrascrizioneVerbale = dataTrascrizioneVerbale;
            Importo = importo;
            DecrementoPunti = decrementoPunti;
            IDAnagrafica = idAnagrafica;
            IDViolazione = idViolazione;
        }

    }
}

GestionaleMunicipale/Controllers/AnagraficaController.cs
using Municipale.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Municipale.Controllers
{
    public class AnagraficaController : Controller
    {
        
        public ActionResult Index()
        {
            List<Anagrafica> anagrafiche = Db.getAnagrafiche();
            
            return View(anagrafiche);
        }

        [HttpGet]
        public ActionResult Create () 
        { 
        
        return View();
        }

        [HttpPost]
        public ActionResult Create(Anagrafica anagrafica)
        {
            if (ModelState.IsValid) 
            { 
                Db.addAnagrafica(anagrafica);
            return RedirectToAction("Index", "Anagrafica");
            }
            else 
            { 
            return View();
            
            }
        }


    }
}

GestionaleMunicipale/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Municipale.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            return View();
        }

        
    }
}

GestionaleMunicipale/Controllers/TipoViolazioneController.cs
using Municipale.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Municipale.Controllers
{
    public class TipoViolazioneController : Controller
    {
        
        public ActionResult Index()
        {
            List<TipoViolazione> Violazioni = Db.GetViolazioni();

            return View(Violazioni);
        }

        [HttpGet]
        public ActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TipoViolazione violazione)
        {

            Db.AddViolazione(violazione);


            return RedirectToAction("Index");
        }

    }
}

GestionaleMunicipale/Controllers/VerbaliController.cs
using Municipale.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Municipale.Controllers
{
    public class VerbaliController : Controller
    {
        
        public ActionResult Index()
        {
            List<Verbale> verbali = Db.GetVerbale();
            return View(verbali);
        }

        [HttpGet]
        public ActionResult Create() 
        {
            List<Anagrafica> anagrafiche = Db.getAnagrafiche();
            List<SelectListItem> dropAnagrafiche = anagrafiche.Select(e => new SelectListItem
            {
                Value = e.IDAnagrafica.ToString(),
                Text = $"{e.Nome} {e.Cognome}"
            }).ToList();
            ViewBag.Anagrafiche = dropAnagrafiche;

            List<TipoViolazione> violazioni = Db.GetViolazioni();
            List<SelectListItem> dropViolazioni = violazioni.Select(e => new SelectListItem
            {
                Value = e.IdViolazione.ToString(),
                Text = e.Descrizione.ToString()
            }).ToList();
            ViewBag.Violazioni = dropViolazioni;




            return View();
        }

        [HttpPost]
        public ActionResult Create(Verbale verbale) 
        { 
            
            Db.addVerbale(verbale);
            return RedirectToAction("Index","Verbali");
        }


        [HttpGet]
        public ActionResult filterImporto () 
        {
            List<Verbale> verbali = Db.GetVerbaleImporto();
        
        return View(verbali);
        
        
        }


        [HttpGet]
        public ActionResult filterAnagrafica()
        {
            List<Anagrafica> Anagrafiche = Db.GetVerbaleAnagrafica();

            return View(Anagrafiche);


        }


        [HttpGet]
        public ActionResult filterPuntiAnagrafica()
        {
            List<Anagrafica> Anagrafiche = Db.GetPuntiAnagrafica();

            return View(Anagrafiche);
        }

        [HttpGet]
        public ActionResult filterVerbaliPunti()
        {
            List<Verbale> verbali = Db.GetVerbaliPunti10();

            return View(verbali);


        }

    }
}

GestionaleMunicipale/Views/Anagrafica/Create.cshtml
@model Municipale.Models.Anagrafica
@using Municipale

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Anagrafica</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-primary" })


        <div class="form-group">
            @Html.LabelFor(model => model.Cognome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cognome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cognome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Indirizzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Indirizzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Indirizzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Citta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Citta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Citta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CAP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CAP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CAP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cod_Fisc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cod_Fisc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cod_Fisc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 my-3 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna ad anagrafiche", "Index", "", new { @class = "nav-link" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionaleMunicipale/Views/Anagrafica/Index.cshtml
@model IEnumerable<Municipale.Models.Anagrafica>
@using Municipale

@{
    ViewBag.Title = "Index";
}



<p>
    @Html.ActionLink("Aggiungi anagrafica", "Create", "Anagrafica", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <thead class="table-primary">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IDAnagrafica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cognome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Indirizzo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Citta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CAP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cod_Fisc)
            </th>

        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model)
        {
            <tr class="table-primary fw-bold">
                <td>
                    @Html.DisplayFor(modelItem => item.IDAnagrafica)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cognome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Indirizzo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Citta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CAP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cod_Fisc)
                </td>

            </tr>
        }
    </tbody>

</table>

GestionaleMunicipale/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@using Municipale




<main class="my-5">
    <div class="my-3">


    </div>
    <div class="container fs-3 ">

        <div class=" my-5 g-3 align-items-center container-fluid">
            <div class="card text-bg-primary mb-3 " >
                <div class="card-header"><h2 class="fw-bold">Verbali</h2></div>
                <div class="card-body">

                    @Html.ActionLink("Lista Verbali", "Index", "Verbali", "", new { @class = "nav-link" })
                    @Html.ActionLink("Aggiungi un verbale", "Create", "Verbali", "", new { @class = "nav-link" })
                </div>
            </div>


            <div class="col d-flex flex-column">
                <div class="card text-bg-primary mb-3 " >
                    <div class="card-header"> <h2 class="fw-bold">Anagrafiche</h2></div>
                    <div class="card-body">
                        @Html.ActionLink("Anagrafiche", "Index", "Anagrafica", "", new { @class = "nav-link" })
                        @Html.ActionLink("Aggiungi anagrafica", "Create", "Anagrafica", "", new { @class = "nav-link" })

                    </div>
                </div>

                <div class="col d-flex flex-column">
                    <div class="card text-bg-primary mb-3 ">
                        <div class="card-header"><h2 class="fw-bold">Violazioni</h2></div>
                        <div class="card-body">
                            @Html.ActionLink("Anagrafiche", "Index", "TipoViolazione", "", new { @class = "nav-link" })
                            @Html.ActionLink("Aggiungi violazione", "Create", "TipoViolazione", "", new { @class = "nav-link" })

                        </div>
                    </div>

                    <div class="col d-flex flex-column">
                        <div class="card text-bg-primary mb-3 ">
                            <div class="card-header"><h2 class="fw-bold">Filtra Risultati</h2></div>
                            <div class="card-body">
                                @Html.ActionLink("Verbali divisi per anagrafica", "filterAnagrafica", "Verbali", "", new { @class = "nav-link" })
                                @Html.ActionLink("Punti decurtati divisi per anagrafica", "filterPuntiAnagrafica", "Verbali", "", new { @class = "nav-link" })
                                @Html.ActionLink("Verbali con più di 10 punti decurtati", "filterVerbaliPunti", "Verbali", "", new { @class = "nav-link" })
                                @Html.ActionLink("Verbali di importo superiore a € 400", "filterImporto", "Verbali", "", new { @class = "nav-link" })

                            </div>
                        </div>


                    </div>
                </div>
                </div>

            </div>
            </div>












</main>

GestionaleMunicipale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary fs-2">
        <div class="container">
            @Html.ActionLink("Polizia Municipale", "Index", "Home", new { area = "" }, new { @class = "navbar-brand fs-1" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 ">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link " })</li>
                    <li>@Html.ActionLink("Verbali", "Index", "Verbali", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Anagrafiche", "Index", "Anagrafica", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Violazioni", "Index", "TipoViolazione", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="bg-primary fs-5 text-light rounded-2">
            <p class=" m-5 p-3 ">&copy; @DateTime.Now.Year Federico Maso - epicode </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GestionaleMunicipale/Views/TipoViolazione/Create.cshtml
@model Municipale.Models.TipoViolazione
@using Municipale

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TipoViolazione</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Descrizione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descrizione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descrizione, "", new { @class = "text-primary" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 my-3 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Torna a Violazioni", "Index", "", new { @class = "nav-link" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionaleMunicipale/Views/TipoViolazione/Index.cshtml
@model IEnumerable<Municipale.Models.TipoViolazione>
@using Municipale

@{
    ViewBag.Title = "Index";
}



<p>
    @Html.ActionLink("Aggiungi violazione", "Create", "TipoViolazione", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <thead class="table-primary">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdViolazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descrizione)
            </th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr class="table-primary fw-bold">
                <td>
                    @Html.DisplayFor(modelItem => item.IdViolazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descrizione)
                </td>

            </tr>
        }
    </tbody>

</table>

GestionaleMunicipale/Views/Verbali/Create.cshtml
@model Municipale.Models.Verbale
@using Municipale

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Verbale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.DataViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataViolazione, new { htmlAttributes = new { Type = "date", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataViolazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IndirizzoViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IndirizzoViolazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IndirizzoViolazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nominativo_Agente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nominativo_Agente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nominativo_Agente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataTrascrizioneVerbale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataTrascrizioneVerbale, new { htmlAttributes = new { Type = "date", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataTrascrizioneVerbale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Importo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Importo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Importo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DecrementoPunti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DecrementoPunti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DecrementoPunti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDAnagrafica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IDAnagrafica, new SelectList(ViewBag.Anagrafiche, "Value", "Text"), "Seleziona Anagrafica", new { @class = "form-control" }),
                @Html.ValidationMessageFor(model => model.IDAnagrafica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IDViolazione, new SelectList(ViewBag.Violazioni, "Value", "Text"), "Seleziona Violazione", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDViolazione, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 my-3 col-md-10">
                <input type="submit" value="Inserisci verbale" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Vai a Verbali", "Index", "", new { @class = "nav-link" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionaleMunicipale/Views/Verbali/Index.cshtml
@model IEnumerable<Municipale.Models.Verbale>
@using Municipale

@{
    ViewBag.Title = "Index";
}



<p>
    @Html.ActionLink("Nuovo verbale", "Create", "", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <thead class="table-primary">

        <tr>

            <th>
                @Html.DisplayNameFor(model => model.DataViolazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomeAnagrafica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CognomeAnagrafica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoViolazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IndirizzoViolazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nominativo_Agente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataTrascrizioneVerbale)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DecrementoPunti)
            </th>


        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr class="table-primary fw-bold">

                <td>
                    @Html.DisplayFor(modelItem => item.DataViolazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeAnagrafica)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CognomeAnagrafica)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoViolazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IndirizzoViolazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nominativo_Agente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataTrascrizioneVerbale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Importo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DecrementoPunti)
                </td>

            </tr>
        }
    </tbody>

</table>

GestionaleMunicipale/Views/Verbali/filterAnagrafica.cshtml
@model IEnumerable<Municipale.Models.Anagrafica>
@using Municipale

@{
    ViewBag.Title = "filterAnagrafica";
}

<h2>Verbali filtrati per anagrafica</h2>

<div class="my-3">
    @Html.ActionLink("Vai a Home", "Index", "Home", "", new { @class = "nav-link" })
</div>
<table class="table">
    <thead class="table-primary">

        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Cognome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.totVerbali)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr class="table-primary fw-bold">

                <td>
                    @Html.DisplayFor(modelItem => item.Cognome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.totVerbali)
                </td>

            </tr>
        }
    </tbody>

</table>